//
//  DataCars.swift
//  Casco
//
//  Created by Fuhrer_SS on 13.09.2020.
//  Copyright © 2020 myself. All rights reserved.
//

import Foundation

var dataCar = [
    "CSX": "Acura",
    "MDX": "Acura",
    "NSX": "Acura",
    "RDX": "Acura",
    "RL": "Acura",
    "RSX": "Acura",
    "SLX": "Acura",
    "TL": "Acura",
    "TSX": "Acura",
    "ZDX": "Acura",
    "145": "Alfa Romeo",
    "146": "Alfa Romeo",
    "147": "Alfa Romeo",
    "149": "Alfa Romeo",
    "155": "Alfa Romeo",
    "156": "Alfa Romeo",
    "159": "Alfa Romeo",
    "166": "Alfa Romeo",
    "8c": "Alfa Romeo",
    "Brera": "Alfa Romeo",
    "Giulietta": "Alfa Romeo",
    "GT": "Alfa Romeo",
    "GTV": "Alfa Romeo",
    "MiTo": "Alfa Romeo",
    "Spider": "Alfa Romeo",
    "DB9": "Aston Martin",
    "V12 Vanquish": "Aston Martin",
    "V8": "Aston Martin",
    "A1": "Audi",
    "A2": "Audi",
    "A3": "Audi",
    "A4": "Audi",
    "A4 Allroad": "Audi",
    "A5": "Audi",
    "A6": "Audi",
    "A6 Allroad": "Audi",
    "A7": "Audi",
    "A8": "Audi",
    "Q3": "Audi",
    "Q5": "Audi",
    "Q7": "Audi",
    "Q8": "Audi",
    "R8": "Audi",
    "RS Q3": "Audi",
    "RS4": "Audi",
    "RS5": "Audi",
    "RS6": "Audi",
    "RS7": "Audi",
    "S3": "Audi",
    "S4": "Audi",
    "S5": "Audi",
    "S6": "Audi",
    "S8": "Audi",
    "TT": "Audi",
    "Arnage": "Bentley",
    "Azure": "Bentley",
    "Continental Flying Spur": "Bentley",
    "Continental GT": "Bentley",
    "1": "BMW",
    "2": "BMW",
    "3": "BMW",
    "3 Gran Turismo": "BMW",
    "4": "BMW",
    "5": "BMW",
    "5 Gran Turismo": "BMW",
    "6": "BMW",
    "7": "BMW",
    "8": "BMW",
    "Gran Coupe": "BMW",
    "M1": "BMW",
    "M3": "BMW",
    "M5": "BMW",
    "M6": "BMW",
    "X1": "BMW",
    "X2": "BMW",
    "X3": "BMW",
    "X4": "BMW",
    "X5": "BMW",
    "X5M": "BMW",
    "X6": "BMW",
    "X6M": "BMW",
    "X7": "BMW",
    "Z3": "BMW",
    "Z4": "BMW",
    "Z8": "BMW",
    "i8": "BMW",
    "2110": "Bogdan",
    "2111": "Bogdan",
    "A1": "Brilliance",
    "BS3": "Brilliance",
    "BS4": "Brilliance",
    "BS6": "Brilliance",
    "M1": "Brilliance",
    "M2": "Brilliance",
    "M3": "Brilliance",
    "Veyron": "Bugatti",
    "F0": "Byd",
    "F1": "Byd",
    "F3": "Byd",
    "F3-R": "Byd",
    "F6": "Byd",
    "F8": "Byd",
    "Flyer": "Byd",
    "ATS": "Cadillac",
    "BLS": "Cadillac",
    "CTS": "Cadillac",
    "CT4": "Cadillac",
    "CT5": "Cadillac",
    "CT6": "Cadillac",
    "DeVille": "Cadillac",
    "DTS": "Cadillac",
    "Escalade": "Cadillac",
    "SRX": "Cadillac",
    "STS": "Cadillac",
    "XLR": "Cadillac",
    "XT4": "Cadillac",
    "XT6": "Cadillac",
    "Flying": "Chang Feng",
    "SUV": "Chang Feng",
    "CS35": "Changan",
    "CS75": "Changan",
    "Eado": "Changan",
    "Raeton": "Changan",
    "SM-8": "Changan",
    "A13": "Chery",
    "A15": "Chery",
    "A21": "Chery",
    "A3": "Chery",
    "Amulet": "Chery",
    "B11": "Chery",
    "B14": "Chery",
    "Bonus": "Chery",
    "Crosseastar": "Chery",
    "Eastar": "Chery",
    "Flagcloud": "Chery",
    "Fora": "Chery",
    "Indis": "Chery",
    "Kimo": "Chery",
    "Langie": "Chery",
    "M11": "Chery",
    "Mikado": "Chery",
    "OrientalSon": "Chery",
    "QQ6": "Chery",
    "S21": "Chery",
    "Sweet": "Chery",
    "T11": "Chery",
    "Tiggo": "Chery",
    "Very": "Chery",
    "Windcloud": "Chery",
    "Alero": "Chevrolet",
    "Astro": "Chevrolet",
    "Avalanche": "Chevrolet",
    "Aveo": "Chevrolet",
    "Blazer": "Chevrolet",
    "Camaro": "Chevrolet",
    "Captiva": "Chevrolet",
    "Cavalier": "Chevrolet",
    "Classic": "Chevrolet",
    "Cobalt": "Chevrolet",
    "Colorado": "Chevrolet",
    "Corvette": "Chevrolet",
    "Cruze": "Chevrolet",
    "Envoy": "Chevrolet",
    "Epica": "Chevrolet",
    "Equinox": "Chevrolet",
    "Evanda": "Chevrolet",
    "Express": "Chevrolet",
    "HHR": "Chevrolet",
    "Impala": "Chevrolet",
    "Lacetti": "Chevrolet",
    "Lanos": "Chevrolet",
    "Lumina": "Chevrolet",
    "Malibu": "Chevrolet",
    "Monte Carlo": "Chevrolet",
    "Niva": "Chevrolet",
    "Nubira": "Chevrolet",
    "Orlando": "Chevrolet",
    "Rezzo": "Chevrolet",
    "Savana": "Chevrolet",
    "Silverado": "Chevrolet",
    "Spark": "Chevrolet",
    "SSR": "Chevrolet",
    "Starcraft": "Chevrolet",
    "Suburban": "Chevrolet",
    "Tahoe": "Chevrolet",
    "Tracker": "Chevrolet",
    "Trailblazer": "Chevrolet",
    "Traverse": "Chevrolet",
    "Uplander": "Chevrolet",
    "Van": "Chevrolet",
    "Viva": "Chevrolet",
    "300C": "Chrysler",
    "300M": "Chrysler",
    "Aspen": "Chrysler",
    "Cirrus": "Chrysler",
    "Concorde": "Chrysler",
    "CrossFire": "Chrysler",
    "Grand Voyager": "Chrysler",
    "Intrepid": "Chrysler",
    "LHS": "Chrysler",
    "Nassau": "Chrysler",
    "Neon": "Chrysler",
    "Pacifica": "Chrysler",
    "PT Cruiser": "Chrysler",
    "Sebring": "Chrysler",
    "Stratus": "Chrysler",
    "Town": "Chrysler",
    "Town&Country": "Chrysler",
    "Voyager": "Chrysler",
    "Aircross": "Citroen",
    "Berlingo": "Citroen",
    "C-crosser": "Citroen",
    "C-Elysee": "Citroen",
    "C1": "Citroen",
    "C2": "Citroen",
    "C3": "Citroen",
    "C3 Picasso": "Citroen",
    "C4": "Citroen",
    "C4 Picasso": "Citroen",
    "C5": "Citroen",
    "C6": "Citroen",
    "C8": "Citroen",
    "DS3": "Citroen",
    "DS4": "Citroen",
    "DS5": "Citroen",
    "Grand C4 Picasso": "Citroen",
    "Jumper": "Citroen",
    "Jumpy": "Citroen",
    "Saxo": "Citroen",
    "Xantia": "Citroen",
    "Xsara": "Citroen",
    "Xsara Picasso": "Citroen",
    "City": "Dadi",
    "Smoothing": "Dadi",
    "Damas": "Daewoo",
    "Espero": "Daewoo",
    "Gentra": "Daewoo",
    "Lacetti": "Daewoo",
    "Lanos": "Daewoo",
    "Leganza": "Daewoo",
    "Magnus": "Daewoo",
    "Matiz": "Daewoo",
    "Nexia": "Daewoo",
    "Nubira": "Daewoo",
    "Rezzo": "Daewoo",
    "Winstorm": "Daewoo",
    "Altis": "Daihatsu",
    "Be-Go": "Daihatsu",
    "Boon": "Daihatsu",
    "Copen": "Daihatsu",
    "Cuore": "Daihatsu",
    "Materia": "Daihatsu",
    "Max": "Daihatsu",
    "Mira": "Daihatsu",
    "Move": "Daihatsu",
    "MoveLatte": "Daihatsu",
    "Naked": "Daihatsu",
    "Pyzar": "Daihatsu",
    "Sirion": "Daihatsu",
    "Storia": "Daihatsu",
    "Terios": "Daihatsu",
    "Trevis": "Daihatsu",
    "YRV": "Daihatsu",
    "On-Do": "Datsun",
    "Mi-Do": "Datsun",
    "Antelope": "Derways",
    "Aurora": "Derways",
    "Cowboy": "Derways",
    "Land Crown": "Derways",
    "Plutus": "Derways",
    "Saladin": "Derways",
    "Shuttle": "Derways",
    "Avenger": "Dodge",
    "Caliber": "Dodge",
    "Caravan": "Dodge",
    "Challenger": "Dodge",
    "Charger": "Dodge",
    "Dakota": "Dodge",
    "Durango": "Dodge",
    "Grand Caravan": "Dodge",
    "Intrepid": "Dodge",
    "Journey": "Dodge",
    "Magnum": "Dodge",
    "Neon": "Dodge",
    "Nitro": "Dodge",
    "Ram": "Dodge",
    "Stratus": "Dodge",
    "Viper": "Dodge",
    "1020": "FAW",
    "1031": "FAW",
    "1041": "FAW",
    "1051": "FAW",
    "6350": "FAW",
    "6371": "FAW",
    "Admiral": "FAW",
    "Besturn": "FAW",
    "HQ3": "FAW",
    "Jetta": "FAW",
    "Jinn": "FAW",
    "Landmark": "FAW",
    "V2": "FAW",
    "V5": "FAW",
    "Vita": "FAW",
    "360": "Ferrari",
    "430": "Ferrari",
    "599": "Ferrari",
    "612": "Ferrari",
    "California": "Ferrari",
    "Enzo": "Ferrari",
    "Maranello": "Ferrari",
    "500": "Fiat",
    "600": "Fiat",
    "Albea": "Fiat",
    "Barchetta": "Fiat",
    "Brava": "Fiat",
    "Bravo": "Fiat",
    "Coupe": "Fiat",
    "Croma": "Fiat",
    "Doblo": "Fiat",
    "Ducato": "Fiat",
    "Fiorino": "Fiat",
    "Freemont": "Fiat",
    "Grande Punto": "Fiat",
    "Linea": "Fiat",
    "Marea": "Fiat",
    "Multipla": "Fiat",
    "Palio": "Fiat",
    "Panda": "Fiat",
    "Panda 4x4": "Fiat",
    "Punto": "Fiat",
    "Scudo": "Fiat",
    "Sedici": "Fiat",
    "Seicento": "Fiat",
    "Siena": "Fiat",
    "Stilo": "Fiat",
    "Ulysse": "Fiat",
    "C-Max": "Ford",
    "Cougar": "Ford",
    "Crown Victoria": "Ford",
    "E-СЃРµСЂРёСЏ": "Ford",
    "Econoline": "Ford",
    "Econovan": "Ford",
    "Edge": "Ford",
    "Escape": "Ford",
    "Escort": "Ford",
    "Excursion": "Ford",
    "Expedition": "Ford",
    "Explorer": "Ford",
    "F-150": "Ford",
    "F-250": "Ford",
    "F-СЃРµСЂРёСЏ": "Ford",
    "Fiesta": "Ford",
    "Five Hundred": "Ford",
    "Flex": "Ford",
    "Focus": "Ford",
    "Focus ST": "Ford",
    "Freestar": "Ford",
    "Freestyle": "Ford",
    "Fusion": "Ford",
    "Galaxy": "Ford",
    "GT": "Ford",
    "Ka": "Ford",
    "Kuga": "Ford",
    "Maverick": "Ford",
    "Mondeo": "Ford",
    "Mustang": "Ford",
    "Puma": "Ford",
    "Ranger": "Ford",
    "S-Max": "Ford",
    "Scorpio": "Ford",
    "Taurus": "Ford",
    "Thunderbird": "Ford",
    "Tourneo": "Ford",
    "Tourneo Connect": "Ford",
    "Transit": "Ford",
    "Transit Connect": "Ford",
    "Windstar": "Ford",
    "Sup": "Foton",
    "3102": "Gaz",
    "3110": "Gaz",
    "31105": "Gaz",
    "SIBER": "Gaz",
    "Atlas": "Geely",
    "Emgrand": "Geely",
    "MK": "Geely",
    "Otaka": "Geely",
    "Vision": "Geely",
    "G70": "Genesis",
    "G80": "Genesis",
    "G90": "Genesis",
    "GV80": "Genesis",
    "Acadia": "GMC",
    "Canyon": "GMC",
    "Envoy": "GMC",
    "Safari": "GMC",
    "Savana": "GMC",
    "Sierra": "GMC",
    "Sonama": "GMC",
    "Yukon": "GMC",
    "Troy": "Gonow",
    "Victor": "Gonow",
    "Coolbear": "Great Wall",
    "Cowry": "Great Wall",
    "Deer": "Great Wall",
    "Florid": "Great Wall",
    "GWPeri": "Great Wall",
    "Hover": "Great Wall",
    "Monster": "Great Wall",
    "Pegasus": "Great Wall",
    "Peri": "Great Wall",
    "RUV": "Great Wall",
    "Safe": "Great Wall",
    "Sailor": "Great Wall",
    "Sing": "Great Wall",
    "Sokol": "Great Wall",
    "SUV": "Great Wall",
    "Wingle": "Great Wall",
    "Brio": "Hafei",
    "Princip": "Hafei",
    "Simbo": "Hafei",
    "3": "Haima",
    "7": "Haima",
    "Accord": "Honda",
    "Accord Crosstour": "Honda",
    "Airwave": "Honda",
    "Avancier": "Honda",
    "Capa": "Honda",
    "City": "Honda",
    "Civic": "Honda",
    "CR-V": "Honda",
    "Crossroad": "Honda",
    "Crosstour": "Honda",
    "Edix": "Honda",
    "Element": "Honda",
    "Elysion": "Honda",
    "Fit": "Honda",
    "FR-V": "Honda",
    "HR-V": "Honda",
    "Insight": "Honda",
    "Inspire": "Honda",
    "Integra": "Honda",
    "Jazz": "Honda",
    "Legend": "Honda",
    "Life": "Honda",
    "Logo": "Honda",
    "MDX": "Honda",
    "Mobilio": "Honda",
    "NSX": "Honda",
    "Odyssey": "Honda",
    "Orthia": "Honda",
    "Passport": "Honda",
    "Pilot": "Honda",
    "Prelude": "Honda",
    "Ridgeline": "Honda",
    "S-MX": "Honda",
    "S2000": "Honda",
    "Saber": "Honda",
    "Shuttle": "Honda",
    "Stepwgn": "Honda",
    "Stream": "Honda",
    "Torneo": "Honda",
    "Vamos": "Honda",
    "Antelope": "Huanghai",
    "H1": "Hummer",
    "H2": "Hummer",
    "H3": "Hummer",
    "Accent": "Hyundai",
    "Creta": "Hyundai",
    "Coupe": "Hyundai",
    "Elantra": "Hyundai",
    "Equus": "Hyundai",
    "Getz": "Hyundai",
    "Grand Starex": "Hyundai",
    "Grandeur": "Hyundai",
    "H1": "Hyundai",
    "I10": "Hyundai",
    "I20": "Hyundai",
    "I30": "Hyundai",
    "I40": "Hyundai",
    "IX35": "Hyundai",
    "IX55": "Hyundai",
    "Palisade": "Hyundai",
    "Porter": "Hyundai",
    "Santa Fe": "Hyundai",
    "Santa Fe Classic": "Hyundai",
    "Solaris": "Hyundai",
    "Sonata": "Hyundai",
    "Starex": "Hyundai",
    "Terracan": "Hyundai",
    "Tiburon": "Hyundai",
    "Tucson": "Hyundai",
    "Veloster": "Hyundai",
    "Verna": "Hyundai",
    "Samand": "Ikco",
    "Soren": "Ikco",
    "Q30": "Infiniti",
    "Q40": "Infiniti",
    "Q60": "Infiniti",
    "QX45": "Infiniti",
    "QX50": "Inxfiniti",
    "QX56": "Infiniti",
    "QX60": "Infiniti",
    "QX70": "Infiniti",
    "QX80": "Infiniti",
    "EX25": "Infiniti",
    "EX35": "Infiniti",
    "EX37": "Infiniti",
    "FX35": "Infiniti",
    "FX37": "Infiniti",
    "FX45": "Infiniti",
    "FX50": "Infiniti",
    "G25": "Infiniti",
    "G35": "Infiniti",
    "G37": "Infiniti",
    "I30": "Infiniti",
    "I35": "Infiniti",
    "JX": "Infiniti",
    "M35": "Infiniti",
    "M37": "Infiniti",
    "M45": "Infiniti",
    "Ascender": "Isuzu",
    "Axiom": "Isuzu",
    "Bighorn": "Isuzu",
    "D-Max": "Isuzu",
    "Mu": "Isuzu",
    "NKR": "Isuzu",
    "NQR": "Isuzu",
    "Rodeo": "Isuzu",
    "Trooper": "Isuzu",
    "Vehicross": "Isuzu",
    "Wizard": "Isuzu",
    "Daily": "Iveco",
    "2126": "Izh",
    "2717": "Izh",
    "HFC1040": "JAC",
    "HFC1045": "JAC",
    "HFC1061": "JAC",
    "Refine": "JAC",
    "Rein": "JAC",
    "E-PACE": "Jaguar",
    "F-PACE": "Jaguar",
    "I-PACE": "Jaguar",
    "E-TYPE": "Jaguar",
    "F-Type": "Jaguar",
    "S-Type": "Jaguar",
    "X-Type": "Jaguar",
    "XF": "Jaguar",
    "XFR": "Jaguar",
    "XJ": "Jaguar",
    "XJR": "Jaguar",
    "XK": "Jaguar",
    "XK8": "Jaguar",
    "XKR": "Jaguar",
    "Cherokee": "Jeep",
    "Commander": "Jeep",
    "Compass": "Jeep",
    "Grand Cherokee": "Jeep",
    "Liberty": "Jeep",
    "Patriot": "Jeep",
    "Wrangler": "Jeep",
    "1032": "JMC",
    "1043": "JMC",
    "1052": "JMC",
    "Baodian": "JMC",
    "Ceed": "Kia",
    "Ceed SW": "Kia",
    "Cerato": "Kia",
    "Magentis": "Kia",
    "Mohave": "Kia",
    "Optima": "Kia",
    "Picanto": "Kia",
    "Pro Ceed": "Kia",
    "Quoris": "Kia",
    "Rio": "Kia",
    "Sorento": "Kia",
    "Sorento Prime": "Kia",
    "Soul": "Kia",
    "Seltos": "Kia",
    "Sportage": "Kia",
    "Stinger": "Kia",
    "Telluride": "Kia",
    "Venga": "Kia",
    "1113 OKA": "Lada",
    "2104": "Lada",
    "2105": "Lada",
    "2106": "Lada",
    "2107": "Lada",
    "2108": "Lada",
    "2109": "Lada",
    "21099": "Lada",
    "2110": "Lada",
    "2111": "Lada",
    "2112": "Lada",
    "2113": "Lada",
    "2114": "Lada",
    "2115": "Lada",
    "2120": "Lada",
    "2121": "Lada",
    "2131": "Lada",
    "2190 GRANTA": "Lada",
    "KALINA": "Lada",
    "Largus": "Lada",
    "PRIORA": "Lada",
    "Vesta": "Lada",
    "Vesta Cross": "Lada",
    "XRAY": "Lada",
    "XRAY Cross": "Lada",
    "Gallardo": "Lamborghini",
    "Murcielago": "Lamborghini",
    "Delta": "Lancia",
    "Kappa": "Lancia",
    "Lybra": "Lancia",
    "Musa": "Lancia",
    "Phedra": "Lancia",
    "Thesis": "Lancia",
    "Y": "Lancia",
    "Ypsilon": "Lancia",
    "Defender": "Land Rover",
    "Discovery": "Land Rover",
    "Evoque": "Land Rover",
    "Freelander": "Land Rover",
    "Range Rover": "Land Rover",
    "Range Rover Sport": "Land Rover",
    "Range Rover Velar": "Land Rover",
    "Vogue": "Land Rover",
    "SUV": "Landwind",
    "CT": "Lexus",
    "ES": "Lexus",
    "GS": "Lexus",
    "GX": "Lexus",
    "IS": "Lexus",
    "IS F": "Lexus",
    "LS": "Lexus",
    "LF": "Lexus",
    "LX": "Lexus",
    "NX": "Lexus",
    "RX": "Lexus",
    "SC": "Lexus",
    "UX": "Lexus",
    "Breez": "Lifan",
    "Smily": "Lifan",
    "Solano": "Lifan",
    "X60": "Lifan",
    "X70": "Lifan",
    "Aviator": "Lincoln",
    "Continental": "Lincoln",
    "LS": "Lincoln",
    "Mark": "Lincoln",
    "Mark LT": "Lincoln",
    "MKX": "Lincoln",
    "MKZ": "Lincoln",
    "Navigator": "Lincoln",
    "TownCar": "Lincoln",
    "Zephyr": "Lincoln",
    "Elise": "Lotus",
    "Exige": "Lotus",
    "7 Suv": "Luxgen",
    "Coupe": "Maserati",
    "Gransport": "Maserati",
    "Granturismo": "Maserati",
    "MC12": "Maserati",
    "Quattroporte": "Maserati",
    "Spyder": "Maserati",
    "57": "Maybach",
    "62": "Maybach",
    "2": "Mazda",
    "3": "Mazda",
    "323": "Mazda",
    "5": "Mazda",
    "6": "Mazda",
    "626": "Mazda",
    "Atenza": "Mazda",
    "Axela": "Mazda",
    "B": "Mazda",
    "B Pickup": "Mazda",
    "B-2500": "Mazda",
    "BT-50": "Mazda",
    "Capella": "Mazda",
    "Carol": "Mazda",
    "Cronos": "Mazda",
    "CX-3": "Mazda",
    "CX-30": "Mazda",
    "CX-5": "Mazda",
    "CX-7": "Mazda",
    "CX-9": "Mazda",
    "Demio": "Mazda",
    "Familia": "Mazda",
    "Lantis": "Mazda",
    "Laputa": "Mazda",
    "Millenia": "Mazda",
    "MPV": "Mazda",
    "MX": "Mazda",
    "MX-5": "Mazda",
    "Premacy": "Mazda",
    "Protege": "Mazda",
    "Roadster": "Mazda",
    "RX": "Mazda",
    "RX-7": "Mazda",
    "RX-8": "Mazda",
    "Scrum Van": "Mazda",
    "Tribute": "Mazda",
    "Verisa": "Mazda",
    "Xedos": "Mazda",
    "100": "Mercedes-Benz",
    "A": "Mercedes-Benz",
    "B": "Mercedes-Benz",
    "C": "Mercedes-Benz",
    "CL": "Mercedes-Benz",
    "CLA": "Mercedes-Benz",
    "CLC": "Mercedes-Benz",
    "CLK": "Mercedes-Benz",
    "CLS": "Mercedes-Benz",
    "E": "Mercedes-Benz",
    "G": "Mercedes-Benz",
    "GL": "Mercedes-Benz",
    "GLA": "Mercedes-Benz",
    "GLB": "Mercedes-Benz",
    "GLC": "Mercedes-Benz",
    "GLE": "Mercedes-Benz",
    "GLK": "Mercedes-Benz",
    "GLS": "Mercedes-Benz",
    "ML": "Mercedes-Benz",
    "R": "Mercedes-Benz",
    "S": "Mercedes-Benz",
    "V": "Mercedes-Benz",
    "SL": "Mercedes-Benz",
    "SLK": "Mercedes-Benz",
    "SLS": "Mercedes-Benz",
    "Sprinter": "Mercedes-Benz",
    "Vaneo": "Mercedes-Benz",
    "Viano": "Mercedes-Benz",
    "Vito": "Mercedes-Benz",
    "X-РєР»Р°СЃСЃ": "Mercedes-Benz",
    "Cougar": "Mercury",
    "Mariner": "Mercury",
    "Montego": "Mercury",
    "Mountaineer": "Mercury",
    "Sable": "Mercury",
    "TF": "MG",
    "ZF": "MG",
    "Cabrio": "Mini",
    "Clubman": "Mini",
    "Cooper": "Mini",
    "Cooper S": "Mini",
    "Countryman": "Mini",
    "John Cooper Works": "Mini",
    "ONE": "Mini",
    "Airtrek": "Mitsubishi",
    "Aspire": "Mitsubishi",
    "ASX": "Mitsubishi",
    "Carisma": "Mitsubishi",
    "Cedia": "Mitsubishi",
    "Challenger": "Mitsubishi",
    "Chariot": "Mitsubishi",
    "Colt": "Mitsubishi",
    "Colt Plus": "Mitsubishi",
    "Delica": "Mitsubishi",
    "Diamante": "Mitsubishi",
    "Dingo": "Mitsubishi",
    "Dion": "Mitsubishi",
    "Eclipse": "Mitsubishi",
    "Eclipse Cross": "Mitsubishi",
    "eK-Wagon": "Mitsubishi",
    "Endeavor": "Mitsubishi",
    "Evox": "Mitsubishi",
    "Galant": "Mitsubishi",
    "Grandis": "Mitsubishi",
    "I-Miev": "Mitsubishi",
    "L 200": "Mitsubishi",
    "L300": "Mitsubishi",
    "L400": "Mitsubishi",
    "Lancer": "Mitsubishi",
    "Lancer evolution": "Mitsubishi",
    "Legnum": "Mitsubishi",
    "Libero": "Mitsubishi",
    "Minica": "Mitsubishi",
    "Minicab": "Mitsubishi",
    "Mirage": "Mitsubishi",
    "Montero": "Mitsubishi",
    "Montero Sport": "Mitsubishi",
    "Outlander": "Mitsubishi",
    "Outlander XL": "Mitsubishi",
    "Pajero": "Mitsubishi",
    "Pajero IO": "Mitsubishi",
    "Pajero Mini": "Mitsubishi",
    "Pajero Pinin": "Mitsubishi",
    "Pajero Sport": "Mitsubishi",
    "RVR": "Mitsubishi",
    "Space Star": "Mitsubishi",
    "Space Wagon": "Mitsubishi",
    "Galue": "Mitsuoka",
    "Nouera": "Mitsuoka",
    "Ray": "Mitsuoka",
    "Ryoga": "Mitsuoka",
    "Viewt": "Mitsuoka",
    "350Z": "Nissan",
    "AD": "Nissan",
    "Almera": "Nissan",
    "Almera Classic": "Nissan",
    "Altima": "Nissan",
    "Armada": "Nissan",
    "Avenir": "Nissan",
    "Bassara": "Nissan",
    "Bluebird": "Nissan",
    "Cabstar": "Nissan",
    "Caravan": "Nissan",
    "Cedric": "Nissan",
    "Cefiro": "Nissan",
    "Cima": "Nissan",
    "Cube": "Nissan",
    "Datsun": "Nissan",
    "Dualis": "Nissan",
    "Expert": "Nissan",
    "FireladyZ": "Nissan",
    "Frontier": "Nissan",
    "Fuga": "Nissan",
    "Gloria": "Nissan",
    "GT": "Nissan",
    "GT-R": "Nissan",
    "Homy": "Nissan",
    "Juke": "Nissan",
    "Lafesta": "Nissan",
    "Laurel": "Nissan",
    "Liberty": "Nissan",
    "March": "Nissan",
    "Maxima": "Nissan",
    "Micra": "Nissan",
    "Mistral": "Nissan",
    "Moco": "Nissan",
    "Murano": "Nissan",
    "Navara": "Nissan",
    "Note": "Nissan",
    "NP 300": "Nissan",
    "Otti": "Nissan",
    "Pathfinder": "Nissan",
    "Patrol": "Nissan",
    "Pickup": "Nissan",
    "Presage": "Nissan",
    "President": "Nissan",
    "Primastar": "Nissan",
    "Primera": "Nissan",
    "Qashqai": "Nissan",
    "Quest": "Nissan",
    "Rogue": "Nissan",
    "Safari": "Nissan",
    "Sentra": "Nissan",
    "Serena": "Nissan",
    "Silvia": "Nissan",
    "Skyline": "Nissan",
    "Sunny": "Nissan",
    "Teana": "Nissan",
    "Terrano": "Nissan",
    "Tiida": "Nissan",
    "Tiida Latio": "Nissan",
    "Tino": "Nissan",
    "Titan": "Nissan",
    "Wingroad": "Nissan",
    "X-Terra": "Nissan",
    "X-Trail": "Nissan",
    "Agila": "Opel",
    "Ampera": "Opel",
    "Antara": "Opel",
    "Astra": "Opel",
    "Combo": "Opel",
    "Corsa": "Opel",
    "Frontera": "Opel",
    "Insignia": "Opel",
    "Meriva": "Opel",
    "Mokka": "Opel",
    "Monterey": "Opel",
    "Movano": "Opel",
    "Omega": "Opel",
    "Signum": "Opel",
    "Tigra": "Opel",
    "Vectra": "Opel",
    "Vita": "Opel",
    "Vivaro": "Opel",
    "Zafira": "Opel",
    "1007": "Peugeot",
    "106": "Peugeot",
    "107": "Peugeot",
    "2008": "Peugeot",
    "206": "Peugeot",
    "207": "Peugeot",
    "208": "Peugeot",
    "3008": "Peugeot",
    "301": "Peugeot",
    "306": "Peugeot",
    "307": "Peugeot",
    "308": "Peugeot",
    "4007": "Peugeot",
    "4008": "Peugeot",
    "406": "Peugeot",
    "407": "Peugeot",
    "408": "Peugeot",
    "5008": "Peugeot",
    "508": "Peugeot",
    "607": "Peugeot",
    "807": "Peugeot",
    "Boxer": "Peugeot",
    "Expert": "Peugeot",
    "Partner": "Peugeot",
    "RCZ": "Peugeot",
    "Bonneville": "Pontiac",
    "G5": "Pontiac",
    "G6": "Pontiac",
    "G8": "Pontiac",
    "Grand": "Pontiac",
    "GTO": "Pontiac",
    "Solstice": "Pontiac",
    "Sunfire": "Pontiac",
    "Torrent": "Pontiac",
    "Vibe": "Pontiac",
    "911": "Porsche",
    "918 Spyder": "Porsche",
    "Boxster": "Porsche",
    "Carrera": "Porsche",
    "Cayenne": "Porsche",
    "Cayman": "Porsche",
    "Macan": "Porsche",
    "Macan": "Porsche",
    "Panamera": "Porsche",
    "Arkana": "Renault",
    "Avantime": "Renault",
    "Clio": "Renault",
    "Duster": "Renault",
    "Espace": "Renault",
    "Estafette": "Renault",
    "Fluence": "Renault",
    "Kangoo": "Renault",
    "Koleos": "Renault",
    "Laguna": "Renault",
    "Laguna Coupe": "Renault",
    "Latitude": "Renault",
    "Logan": "Renault",
    "Mascott": "Renault",
    "Master": "Renault",
    "Megane": "Renault",
    "Megane Coupe": "Renault",
    "Modus": "Renault",
    "Safrane": "Renault",
    "Sandero": "Renault",
    "Sandero Stepway": "Renault",
    "Scenic": "Renault",
    "sr": "Renault",
    "Symbol": "Renault",
    "Trafic": "Renault",
    "Twingo": "Renault",
    "Vel Satis": "Renault",
    "Z": "Renault",
    "Ghost": "Rolls-Royce",
    "Phantom": "Rolls-Royce",
    "25": "Rover",
    "400": "Rover",
    "45": "Rover",
    "75": "Rover",
    "Streetwise": "Rover",
    "9-2X": "Saab",
    "9-3": "Saab",
    "9-5": "Saab",
    "9-7": "Saab",
    "9-7X": "Saab",
    "Ion": "Saturn",
    "SC": "Saturn",
    "SL": "Saturn",
    "Vue": "Saturn",
    "TC": "Scion",
    "XA": "Scion",
    "XB": "Scion",
    "Alhambra": "Seat",
    "Altea": "Seat",
    "Arosa": "Seat",
    "Cordoba": "Seat",
    "Exeo": "Seat",
    "FR": "Seat",
    "Freetrack": "Seat",
    "Ibiza": "Seat",
    "Leon": "Seat",
    "Toledo": "Seat",
    "Fabia": "Skoda",
    "Felicia": "Skoda",
    "Kamiq": "Skoda",
    "Karoq": "Skoda",
    "Kodiaq": "Skoda",
    "Octavia": "Skoda",
    "Praktik": "Skoda",
    "Rapid": "Skoda",
    "Roomster": "Skoda",
    "Superb": "Skoda",
    "Yeti": "Skoda",
    "Maple": "SMA",
    "City": "Smart",
    "Forfour": "Smart",
    "Fortwo": "Smart",
    "Pulse": "Smart",
    "Pure": "Smart",
    "Roadster": "Smart",
    "Actyon": "Ssang Yong",
    "Actyon Sports": "Ssang Yong",
    "Istana": "Ssang Yong",
    "Korando": "Ssang Yong",
    "Kyron": "Ssang Yong",
    "Musso": "Ssang Yong",
    "Rexton": "Ssang Yong",
    "Rodius": "Ssang Yong",
    "Stavic": "Ssang Yong",
    "Ascent": "Subaru",
    "BRZ": "Subaru",
    "Forester": "Subaru",
    "Impreza": "Subaru",
    "Impreza WRX": "Subaru",
    "Impreza XV": "Subaru",
    "Legacy": "Subaru",
    "Outback": "Subaru",
    "Pleo": "Subaru",
    "R1": "Subaru",
    "R2": "Subaru",
    "Traviq": "Subaru",
    "Tribeca": "Subaru",
    "XV": "Subaru",
    "Aerio": "Suzuki",
    "Alto": "Suzuki",
    "Baleno": "Suzuki",
    "Cultus": "Suzuki",
    "Escudo": "Suzuki",
    "Every": "Suzuki",
    "Grand Vitara": "Suzuki",
    "Ignis": "Suzuki",
    "Jimny": "Suzuki",
    "Kei": "Suzuki",
    "Kizashi": "Suzuki",
    "Liana": "Suzuki",
    "Solio": "Suzuki",
    "Splash": "Suzuki",
    "Swift": "Suzuki",
    "SX4": "Suzuki",
    "Twin": "Suzuki",
    "Vitara": "Suzuki",
    "Wagon": "Suzuki",
    "XL-7": "Suzuki",
    "Aquila": "Tagaz",
    "C10": "Tagaz",
    "C100 VEGA": "Tagaz",
    "C190": "Tagaz",
    "C30": "Tagaz",
    "ROAD PARTNER": "Tagaz",
    "TAGER": "Tagaz",
    "TIGGO": "Tagaz",
    "VORTEX CORDA": "Tagaz",
    "VORTEX ESTINA": "Tagaz",
    "VORTEX TINGO": "Tagaz",
    "Century": "Tianma",
    "Admiral": "Tianye",
    "Alphard": "Toyota",
    "Altezza": "Toyota",
    "Aristo": "Toyota",
    "Auris": "Toyota",
    "Avensis": "Toyota",
    "Caldina": "Toyota",
    "Camry": "Toyota",
    "Corolla": "Toyota",
    "Corsa": "Toyota",
    "Cresta": "Toyota",
    "Crown": "Toyota",
    "C-HR": "Toyota",
    "FJ Cruiser": "Toyota",
    "Fortuner": "Toyota",
    "Highlander": "Toyota",
    "Hilux": "Toyota",
    "Land Cruiser": "Toyota",
    "Land Cruiser Prado": "Toyota",
    "Prius": "Toyota",
    "RAV4": "Toyota",
    "Sequoia": "Toyota",
    "Supra": "Toyota",
    "Town Ace": "Toyota",
    "Tundra": "Toyota",
    "Venza": "Toyota",
    "Verossa": "Toyota",
    "Verso": "Toyota",
    "Yaris": "Toyota",
    "3151": "Uaz",
    "HUNTER": "Uaz",
    "PATRIOT": "Uaz",
    "PATRIOT SPORT": "Uaz",
    "PICKUP": "Uaz",
    "Amarok": "Volkswagen",
    "Arteon": "Volkswagen",
    "Beetle": "Volkswagen",
    "Bora": "Volkswagen",
    "Caddy": "Volkswagen",
    "California": "Volkswagen",
    "Caravelle": "Volkswagen",
    "Crafter": "Volkswagen",
    "Crossgolf": "Volkswagen",
    "EOS": "Volkswagen",
    "Golf": "Volkswagen",
    "Golf Plus": "Volkswagen",
    "Jetta": "Volkswagen",
    "Multivan": "Volkswagen",
    "Passat": "Volkswagen",
    "Passat GT": "Volkswagen",
    "Passat CC": "Volkswagen",
    "Phaeton": "Volkswagen",
    "Pointer": "Volkswagen",
    "Polo": "Volkswagen",
    "Polo Sedan": "Volkswagen",
    "Scirocco": "Volkswagen",
    "Sharan": "Volkswagen",
    "Shuttle": "Volkswagen",
    "Teramont": "Volkswagen",
    "Tiguan": "Volkswagen",
    "Touareg": "Volkswagen",
    "Touran": "Volkswagen",
    "Transporter": "Volkswagen",
    "T-rock": "Volkswagen",
    "C30": "Volvo",
    "C70": "Volvo",
    "S30": "Volvo",
    "S40": "Volvo",
    "S60": "Volvo",
    "S70": "Volvo",
    "S80": "Volvo",
    "S90": "Volvo",
    "V40": "Volvo",
    "V50": "Volvo",
    "V60": "Volvo",
    "V70": "Volvo",
    "XC40": "Volvo",
    "XC60": "Volvo",
    "XC70": "Volvo",
    "XC90": "Volvo",
    "PickUp X3": "Xinkai",
    "SR-V X3": "Xinkai",
    "SUV X3": "Xinkai",
    "Flying": "Yangzi",
    "CHANCE": "Zaz",
    "SENS": "Zaz",
    "Vida": "Zaz",
    "Grand Tiger": "ZX"
];             
